services:
  wine-color-predictor:
    image: farhan64/dsci522-2425-22-wine-chromatic-profile:latest 
    ports:
      - "8888:8888" 
    volumes:
      - "${PWD}:/app/data"
    working_dir: /app
    deploy:
      resources:
        limits:
          memory: 8G
    platform: linux/amd64