name: wine
channels:
  - conda-forge
  - defaults
dependencies:
  - altair-all=5.4
  - pandera=0.20.2
  - ipykernel=6.29.5
  - matplotlib[version='3.9.2']
  - nb_conda_kernels=2.5.1
  - numpy=2.1.3
  - pandas=2.2.3
  - pip=24.3.1
  - python=3.11
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - ucimlrepo=0.0.7
  - vega_datasets=0.9.0
  - vegafusion=1.6.9
  - pip:
      - altair_ally>=0.1.1
      - deepchecks>=0.18


